#loc = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":9:0)
module {
  tt.func public @gather_simple(%arg0: !tt.ptr<i32> loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":9:0), %arg1: !tt.ptr<i32> loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":9:0), %arg2: !tt.ptr<i32> loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":9:0)) attributes {noinline = false} {
    %0 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32> loc(#loc1)
    %1 = tt.splat %arg0 : !tt.ptr<i32> -> tensor<8x!tt.ptr<i32>> loc(#loc2)
    %2 = tt.addptr %1, %0 : tensor<8x!tt.ptr<i32>>, tensor<8xi32> loc(#loc2)
    %3 = tt.splat %arg1 : !tt.ptr<i32> -> tensor<8x!tt.ptr<i32>> loc(#loc3)
    %4 = tt.addptr %3, %0 : tensor<8x!tt.ptr<i32>>, tensor<8xi32> loc(#loc3)
    %5 = tt.cat %2, %4 : tensor<8x!tt.ptr<i32>> -> tensor<16x!tt.ptr<i32>> loc(#loc4)
    %6 = tt.load %5 : tensor<16x!tt.ptr<i32>> loc(#loc5)
    %7 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32> loc(#loc6)
    %8 = tt.splat %arg2 : !tt.ptr<i32> -> tensor<16x!tt.ptr<i32>> loc(#loc7)
    %9 = tt.addptr %8, %7 : tensor<16x!tt.ptr<i32>>, tensor<16xi32> loc(#loc7)
    tt.store %9, %6 : tensor<16x!tt.ptr<i32>> loc(#loc8)
    tt.return loc(#loc9)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":10:24)
#loc2 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":11:21)
#loc3 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":12:21)
#loc4 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":13:28)
#loc5 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":14:16)
#loc6 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":18:28)
#loc7 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":19:20)
#loc8 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":19:30)
#loc9 = loc("/home/nhat/github/triton_shared/python/examples/test_multiple_bases.py":19:4)