// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// RUN: triton-shared-opt --triton-to-linalg-experimental %s | FileCheck %s

// Make sure extract_slice and subview is generated with correct offsets and strides.

// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0, d1) -> (d0, 0)>
// CHECK: #[[$ATTR_2:.+]] = affine_map<(d0, d1) -> (d0, d1)>
// CHECK-LABEL:   func.func @row_gather3(
// CHECK-SAME:                           %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                           %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                           %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                           %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG13:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG14:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG15:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG16:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG17:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG18:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG19:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG20:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG21:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[VAL_0:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_1:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_2:.*]] = arith.constant 1 : i32
// CHECK:           %[[VAL_3:.*]] = arith.constant 64 : index
// CHECK:           %[[VAL_4:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[VAL_5:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_6:.*]] = arith.constant 64 : i32
// CHECK:           %[[VAL_7:.*]] = tensor.empty() : tensor<64x64xf32>
// CHECK:           %[[VAL_8:.*]] = tensor.collapse_shape %[[VAL_7]] {{\[\[}}0, 1]] : tensor<64x64xf32> into tensor<4096xf32>
// CHECK:           %[[VAL_9:.*]] = linalg.fill ins(%[[VAL_4]] : f32) outs(%[[VAL_8]] : tensor<4096xf32>) -> tensor<4096xf32>
// CHECK:           %[[VAL_10:.*]] = tensor.expand_shape %[[VAL_9]] {{\[\[}}0, 1]] output_shape [64, 64] : tensor<4096xf32> into tensor<64x64xf32>
// CHECK:           %[[VAL_11:.*]] = arith.muli %[[ARG19]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_12:.*]] = tensor.empty() : tensor<64xi32>
// CHECK:           %[[VAL_13:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_12]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_14:.*]]: i32):
// CHECK:             %[[VAL_15:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_16:.*]] = arith.index_cast %[[VAL_15]] : index to i32
// CHECK:             linalg.yield %[[VAL_16]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_17:.*]] = linalg.fill ins(%[[VAL_11]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_18:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_17]], %[[VAL_13]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_17]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_19:.*]]: i32, %[[VAL_20:.*]]: i32, %[[VAL_21:.*]]: i32):
// CHECK:             %[[VAL_22:.*]] = arith.addi %[[VAL_19]], %[[VAL_20]] : i32
// CHECK:             linalg.yield %[[VAL_22]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_23:.*]] = arith.muli %[[ARG20]], %[[VAL_6]] : i32
// CHECK:           %[[VAL_24:.*]] = arith.index_cast %[[VAL_23]] : i32 to index
// CHECK:           %[[VAL_25:.*]] = arith.muli %[[ARG3]], %[[ARG4]] : i32
// CHECK:           %[[VAL_26:.*]] = linalg.fill ins(%[[VAL_25]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_27:.*]] = tensor.empty() : tensor<64xi1>
// CHECK:           %[[VAL_28:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_18]], %[[VAL_26]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_27]] : tensor<64xi1>) {
// CHECK:           ^bb0(%[[VAL_29:.*]]: i32, %[[VAL_30:.*]]: i32, %[[VAL_31:.*]]: i1):
// CHECK:             %[[VAL_32:.*]] = arith.cmpi slt, %[[VAL_29]], %[[VAL_30]] : i32
// CHECK:             linalg.yield %[[VAL_32]] : i1
// CHECK:           } -> tensor<64xi1>
// CHECK:           %[[VAL_33:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_18]], %[[VAL_26]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_18]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_34:.*]]: i32, %[[VAL_35:.*]]: i32, %[[VAL_36:.*]]: i32):
// CHECK:             %[[VAL_37:.*]] = arith.divsi %[[VAL_34]], %[[VAL_35]] : i32
// CHECK:             linalg.yield %[[VAL_37]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_38:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_18]], %[[VAL_26]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_18]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_39:.*]]: i32, %[[VAL_40:.*]]: i32, %[[VAL_41:.*]]: i32):
// CHECK:             %[[VAL_42:.*]] = arith.remsi %[[VAL_39]], %[[VAL_40]] : i32
// CHECK:             linalg.yield %[[VAL_42]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_43:.*]] = linalg.fill ins(%[[ARG4]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_44:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_38]], %[[VAL_43]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_38]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_45:.*]]: i32, %[[VAL_46:.*]]: i32, %[[VAL_47:.*]]: i32):
// CHECK:             %[[VAL_48:.*]] = arith.divsi %[[VAL_45]], %[[VAL_46]] : i32
// CHECK:             linalg.yield %[[VAL_48]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_49:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_38]], %[[VAL_43]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_38]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_50:.*]]: i32, %[[VAL_51:.*]]: i32, %[[VAL_52:.*]]: i32):
// CHECK:             %[[VAL_53:.*]] = arith.remsi %[[VAL_50]], %[[VAL_51]] : i32
// CHECK:             linalg.yield %[[VAL_53]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_54:.*]] = scf.for %[[VAL_55:.*]] = %[[VAL_5]] to %[[ARG6]] step %[[VAL_2]] iter_args(%[[VAL_56:.*]] = %[[VAL_10]]) -> (tensor<64x64xf32>)  : i32 {
// CHECK:             %[[VAL_57:.*]] = linalg.fill ins(%[[ARG7]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_58:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_33]], %[[VAL_57]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_33]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_59:.*]]: i32, %[[VAL_60:.*]]: i32, %[[VAL_61:.*]]: i32):
// CHECK:               %[[VAL_62:.*]] = arith.muli %[[VAL_59]], %[[VAL_60]] : i32
// CHECK:               linalg.yield %[[VAL_62]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_63:.*]] = linalg.fill ins(%[[ARG8]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_64:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_44]], %[[VAL_63]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_44]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_65:.*]]: i32, %[[VAL_66:.*]]: i32, %[[VAL_67:.*]]: i32):
// CHECK:               %[[VAL_68:.*]] = arith.muli %[[VAL_65]], %[[VAL_66]] : i32
// CHECK:               linalg.yield %[[VAL_68]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_69:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_58]], %[[VAL_64]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_58]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_70:.*]]: i32, %[[VAL_71:.*]]: i32, %[[VAL_72:.*]]: i32):
// CHECK:               %[[VAL_73:.*]] = arith.addi %[[VAL_70]], %[[VAL_71]] : i32
// CHECK:               linalg.yield %[[VAL_73]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_74:.*]] = linalg.fill ins(%[[ARG9]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_75:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_49]], %[[VAL_74]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_49]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_76:.*]]: i32, %[[VAL_77:.*]]: i32, %[[VAL_78:.*]]: i32):
// CHECK:               %[[VAL_79:.*]] = arith.muli %[[VAL_76]], %[[VAL_77]] : i32
// CHECK:               linalg.yield %[[VAL_79]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_80:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_69]], %[[VAL_75]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_69]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_81:.*]]: i32, %[[VAL_82:.*]]: i32, %[[VAL_83:.*]]: i32):
// CHECK:               %[[VAL_84:.*]] = arith.addi %[[VAL_81]], %[[VAL_82]] : i32
// CHECK:               linalg.yield %[[VAL_84]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_85:.*]] = linalg.fill ins(%[[VAL_55]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_86:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_80]], %[[VAL_85]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_80]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_87:.*]]: i32, %[[VAL_88:.*]]: i32, %[[VAL_89:.*]]: i32):
// CHECK:               %[[VAL_90:.*]] = arith.addi %[[VAL_87]], %[[VAL_88]] : i32
// CHECK:               linalg.yield %[[VAL_90]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_91:.*]] = memref.cast %[[ARG0]] : memref<*xf32> to memref<?xf32>
// CHECK:             %[[VAL_92:.*]] = bufferization.to_tensor %[[VAL_91]] restrict : memref<?xf32> to tensor<?xf32>
// CHECK:             %[[VAL_93:.*]] = tensor.empty() : tensor<64xf32>
// CHECK:             %[[VAL_94:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_86]], %[[VAL_28]] : tensor<64xi32>, tensor<64xi1>) outs(%[[VAL_93]] : tensor<64xf32>) {
// CHECK:             ^bb0(%[[VAL_95:.*]]: i32, %[[VAL_96:.*]]: i1, %[[VAL_97:.*]]: f32):
// CHECK:               %[[VAL_98:.*]] = scf.if %[[VAL_96]] -> (f32) {
// CHECK:                 %[[VAL_99:.*]] = arith.index_cast %[[VAL_95]] : i32 to index
// CHECK:                 %[[VAL_100:.*]] = tensor.extract %[[VAL_92]]{{\[}}%[[VAL_99]]] : tensor<?xf32>
// CHECK:                 scf.yield %[[VAL_100]] : f32
// CHECK:               } else {
// CHECK:                 scf.yield %[[VAL_4]] : f32
// CHECK:               }
// CHECK:               linalg.yield %[[VAL_98]] : f32
// CHECK:             } -> tensor<64xf32>
// CHECK:             %[[VAL_101:.*]] = arith.index_cast %[[ARG12]] : i32 to index
// CHECK:             %[[VAL_102:.*]] = arith.muli %[[VAL_24]], %[[VAL_101]] : index
// CHECK:             %[[VAL_103:.*]] = linalg.fill ins(%[[ARG10]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_104:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_44]], %[[VAL_103]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_44]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_105:.*]]: i32, %[[VAL_106:.*]]: i32, %[[VAL_107:.*]]: i32):
// CHECK:               %[[VAL_108:.*]] = arith.muli %[[VAL_105]], %[[VAL_106]] : i32
// CHECK:               linalg.yield %[[VAL_108]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_109:.*]] = linalg.fill ins(%[[ARG11]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:             %[[VAL_110:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_49]], %[[VAL_109]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_49]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_111:.*]]: i32, %[[VAL_112:.*]]: i32, %[[VAL_113:.*]]: i32):
// CHECK:               %[[VAL_114:.*]] = arith.muli %[[VAL_111]], %[[VAL_112]] : i32
// CHECK:               linalg.yield %[[VAL_114]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_115:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_104]], %[[VAL_110]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_104]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_116:.*]]: i32, %[[VAL_117:.*]]: i32, %[[VAL_118:.*]]: i32):
// CHECK:               %[[VAL_119:.*]] = arith.addi %[[VAL_116]], %[[VAL_117]] : i32
// CHECK:               linalg.yield %[[VAL_119]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_120:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_115]], %[[VAL_85]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_115]] : tensor<64xi32>) {
// CHECK:             ^bb0(%[[VAL_121:.*]]: i32, %[[VAL_122:.*]]: i32, %[[VAL_123:.*]]: i32):
// CHECK:               %[[VAL_124:.*]] = arith.addi %[[VAL_121]], %[[VAL_122]] : i32
// CHECK:               linalg.yield %[[VAL_124]] : i32
// CHECK:             } -> tensor<64xi32>
// CHECK:             %[[VAL_125:.*]] = arith.index_cast %[[VAL_11]] : i32 to index
// CHECK:             %[[VAL_126:.*]] = arith.addi %[[VAL_125]], %[[VAL_3]] : index
// CHECK:             %[[VAL_127:.*]] = arith.index_cast %[[VAL_25]] : i32 to index
// CHECK:             %[[VAL_128:.*]] = arith.minsi %[[VAL_126]], %[[VAL_127]] : index
// CHECK:             %[[VAL_129:.*]] = arith.maxsi %[[VAL_128]], %[[VAL_125]] : index
// CHECK:             %[[VAL_130:.*]] = arith.subi %[[VAL_129]], %[[VAL_125]] : index
// CHECK:             %[[VAL_131:.*]] = arith.addi %[[VAL_24]], %[[VAL_3]] : index
// CHECK:             %[[VAL_132:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:             %[[VAL_133:.*]] = arith.minsi %[[VAL_131]], %[[VAL_132]] : index
// CHECK:             %[[VAL_134:.*]] = arith.maxsi %[[VAL_133]], %[[VAL_24]] : index
// CHECK:             %[[VAL_135:.*]] = arith.subi %[[VAL_134]], %[[VAL_24]] : index
// CHECK:             %[[VAL_136:.*]] = arith.minsi %[[VAL_130]], %[[VAL_3]] : index
// CHECK:             %[[VAL_137:.*]] = arith.minsi %[[VAL_135]], %[[VAL_3]] : index
// CHECK:             %[[VAL_138:.*]] = memref.alloc() : memref<64x64xf32>
// CHECK:             %[[VAL_139:.*]] = arith.cmpi slt, %[[VAL_136]], %[[VAL_3]] : index
// CHECK:             %[[VAL_140:.*]] = arith.cmpi slt, %[[VAL_137]], %[[VAL_3]] : index
// CHECK:             %[[VAL_141:.*]] = arith.ori %[[VAL_139]], %[[VAL_140]] : i1
// CHECK:             scf.if %[[VAL_141]] {
// CHECK:               %[[VAL_142:.*]] = memref.collapse_shape %[[VAL_138]] {{\[\[}}0, 1]] : memref<64x64xf32> into memref<4096xf32>
// CHECK:               linalg.fill ins(%[[VAL_4]] : f32) outs(%[[VAL_142]] : memref<4096xf32>)
// CHECK:             }
// CHECK:             %[[VAL_143:.*]] = arith.minsi %[[VAL_136]], %[[VAL_3]] : index
// CHECK:             scf.for %[[VAL_144:.*]] = %[[VAL_1]] to %[[VAL_143]] step %[[VAL_0]] {
// CHECK:               %[[VAL_145:.*]] = tensor.extract %[[VAL_120]]{{\[}}%[[VAL_144]]] : tensor<64xi32>
// CHECK:               %[[VAL_146:.*]] = arith.index_cast %[[VAL_145]] : i32 to index
// CHECK:               %[[VAL_147:.*]] = arith.addi %[[VAL_146]], %[[VAL_102]] : index
// CHECK:               %[[VAL_148:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: {{\[}}%[[VAL_147]]], sizes: [1, 64], strides: [1, %[[VAL_101]]] : memref<*xf32> to memref<1x64xf32, strided<[1, ?], offset: ?>>
// CHECK:               %[[VAL_149:.*]] = memref.subview %[[VAL_148]][0, 0] [1, %[[VAL_137]]] [1, 1] : memref<1x64xf32, strided<[1, ?], offset: ?>> to memref<1x?xf32, strided<[1, ?], offset: ?>>
// CHECK:               %[[VAL_150:.*]] = memref.subview %[[VAL_138]]{{\[}}%[[VAL_144]], 0] [1, %[[VAL_137]]] [1, 1] : memref<64x64xf32> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:               memref.copy %[[VAL_149]], %[[VAL_150]] : memref<1x?xf32, strided<[1, ?], offset: ?>> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:             }
// CHECK:             %[[VAL_151:.*]] = bufferization.to_tensor %[[VAL_138]] restrict writable : memref<64x64xf32> to tensor<64x64xf32>
// CHECK:             %[[VAL_152:.*]] = tensor.expand_shape %[[VAL_94]] {{\[\[}}0, 1]] output_shape [64, 1] : tensor<64xf32> into tensor<64x1xf32>
// CHECK:             %[[VAL_153:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_152]] : tensor<64x1xf32>) outs(%[[VAL_7]] : tensor<64x64xf32>) attrs =  {broadcastDims = array<i64: 1>} {
// CHECK:             ^bb0(%[[VAL_154:.*]]: f32, %[[VAL_155:.*]]: f32):
// CHECK:               linalg.yield %[[VAL_154]] : f32
// CHECK:             } -> tensor<64x64xf32>
// CHECK:             %[[VAL_156:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_2]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_153]], %[[VAL_151]] : tensor<64x64xf32>, tensor<64x64xf32>) outs(%[[VAL_153]] : tensor<64x64xf32>) {
// CHECK:             ^bb0(%[[VAL_157:.*]]: f32, %[[VAL_158:.*]]: f32, %[[VAL_159:.*]]: f32):
// CHECK:               %[[VAL_160:.*]] = arith.mulf %[[VAL_157]], %[[VAL_158]] : f32
// CHECK:               linalg.yield %[[VAL_160]] : f32
// CHECK:             } -> tensor<64x64xf32>
// CHECK:             %[[VAL_161:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_2]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_56]], %[[VAL_156]] : tensor<64x64xf32>, tensor<64x64xf32>) outs(%[[VAL_56]] : tensor<64x64xf32>) {
// CHECK:             ^bb0(%[[VAL_162:.*]]: f32, %[[VAL_163:.*]]: f32, %[[VAL_164:.*]]: f32):
// CHECK:               %[[VAL_165:.*]] = arith.addf %[[VAL_162]], %[[VAL_163]] : f32
// CHECK:               linalg.yield %[[VAL_165]] : f32
// CHECK:             } -> tensor<64x64xf32>
// CHECK:             scf.yield %[[VAL_161]] : tensor<64x64xf32>
// CHECK:           }
// CHECK:           %[[VAL_166:.*]] = linalg.fill ins(%[[ARG13]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_167:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_33]], %[[VAL_166]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_33]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_168:.*]]: i32, %[[VAL_169:.*]]: i32, %[[VAL_170:.*]]: i32):
// CHECK:             %[[VAL_171:.*]] = arith.muli %[[VAL_168]], %[[VAL_169]] : i32
// CHECK:             linalg.yield %[[VAL_171]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_172:.*]] = linalg.fill ins(%[[ARG14]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_173:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_44]], %[[VAL_172]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_44]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_174:.*]]: i32, %[[VAL_175:.*]]: i32, %[[VAL_176:.*]]: i32):
// CHECK:             %[[VAL_177:.*]] = arith.muli %[[VAL_174]], %[[VAL_175]] : i32
// CHECK:             linalg.yield %[[VAL_177]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_178:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_167]], %[[VAL_173]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_167]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_179:.*]]: i32, %[[VAL_180:.*]]: i32, %[[VAL_181:.*]]: i32):
// CHECK:             %[[VAL_182:.*]] = arith.addi %[[VAL_179]], %[[VAL_180]] : i32
// CHECK:             linalg.yield %[[VAL_182]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_183:.*]] = linalg.fill ins(%[[ARG15]] : i32) outs(%[[VAL_12]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[VAL_184:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_49]], %[[VAL_183]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_49]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_185:.*]]: i32, %[[VAL_186:.*]]: i32, %[[VAL_187:.*]]: i32):
// CHECK:             %[[VAL_188:.*]] = arith.muli %[[VAL_185]], %[[VAL_186]] : i32
// CHECK:             linalg.yield %[[VAL_188]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_189:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_178]], %[[VAL_184]] : tensor<64xi32>, tensor<64xi32>) outs(%[[VAL_178]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_190:.*]]: i32, %[[VAL_191:.*]]: i32, %[[VAL_192:.*]]: i32):
// CHECK:             %[[VAL_193:.*]] = arith.addi %[[VAL_190]], %[[VAL_191]] : i32
// CHECK:             linalg.yield %[[VAL_193]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[VAL_194:.*]] = arith.index_cast %[[VAL_11]] : i32 to index
// CHECK:           %[[VAL_195:.*]] = arith.addi %[[VAL_194]], %[[VAL_3]] : index
// CHECK:           %[[VAL_196:.*]] = arith.index_cast %[[VAL_25]] : i32 to index
// CHECK:           %[[VAL_197:.*]] = arith.minsi %[[VAL_195]], %[[VAL_196]] : index
// CHECK:           %[[VAL_198:.*]] = arith.maxsi %[[VAL_197]], %[[VAL_194]] : index
// CHECK:           %[[VAL_199:.*]] = arith.subi %[[VAL_198]], %[[VAL_194]] : index
// CHECK:           %[[VAL_200:.*]] = arith.addi %[[VAL_24]], %[[VAL_3]] : index
// CHECK:           %[[VAL_201:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:           %[[VAL_202:.*]] = arith.minsi %[[VAL_200]], %[[VAL_201]] : index
// CHECK:           %[[VAL_203:.*]] = arith.maxsi %[[VAL_202]], %[[VAL_24]] : index
// CHECK:           %[[VAL_204:.*]] = arith.subi %[[VAL_203]], %[[VAL_24]] : index
// CHECK:           %[[VAL_205:.*]] = arith.minsi %[[VAL_199]], %[[VAL_3]] : index
// CHECK:           %[[VAL_206:.*]] = arith.minsi %[[VAL_204]], %[[VAL_3]] : index
// CHECK:           %[[VAL_207:.*]] = arith.minsi %[[VAL_205]], %[[VAL_3]] : index
// CHECK:           scf.for %[[VAL_208:.*]] = %[[VAL_1]] to %[[VAL_207]] step %[[VAL_0]] {
// CHECK:             %[[VAL_209:.*]] = tensor.extract %[[VAL_189]]{{\[}}%[[VAL_208]]] : tensor<64xi32>
// CHECK:             %[[VAL_210:.*]] = arith.index_cast %[[VAL_209]] : i32 to index
// CHECK:             %[[VAL_211:.*]] = tensor.extract_slice %[[VAL_54]]{{\[}}%[[VAL_208]], 0] [1, %[[VAL_206]]] [1, 1] : tensor<64x64xf32> to tensor<1x?xf32>
// CHECK:             %[[VAL_212:.*]] = arith.addi %[[VAL_210]], %[[VAL_24]] : index
// CHECK:             %[[VAL_213:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: {{\[}}%[[VAL_212]]], sizes: [1, 64], strides: [1, 1] : memref<*xf32> to memref<1x64xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_214:.*]] = memref.subview %[[VAL_213]][0, 0] [1, %[[VAL_206]]] [1, 1] : memref<1x64xf32, strided<[1, 1], offset: ?>> to memref<1x?xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_215:.*]] = memref.cast %[[VAL_214]] : memref<1x?xf32, strided<[1, 1], offset: ?>> to memref<1x?xf32, strided<[?, ?], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[VAL_211]] in writable %[[VAL_215]] : (tensor<1x?xf32>, memref<1x?xf32, strided<[?, ?], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           return

module attributes {} {
  tt.func public @row_gather3(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: !tt.ptr<f32>, %arg3: i32, %arg4: i32, %arg5: i32 , %arg6: i32 , %arg7: i32 , %arg8: i32 , %arg9: i32 , %arg10: i32 , %arg11: i32 , %arg12: i32 , %arg13: i32 , %arg14: i32 , %arg15: i32 ) attributes {noinline = false} {
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %cst = arith.constant dense<0.000000e+00> : tensor<64x64xf32>
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<64xf32>
    %c64_i32 = arith.constant 64 : i32
    %0 = tt.get_program_id x : i32
    %1 = tt.get_program_id y : i32
    %2 = arith.muli %0, %c64_i32 : i32
    %3 = tt.make_range {end = 64 : i32, start = 0 : i32} : tensor<64xi32>
    %4 = tt.splat %2 : i32 -> tensor<64xi32>
    %5 = arith.addi %4, %3 : tensor<64xi32>
    %6 = arith.muli %1, %c64_i32 : i32
    %7 = tt.splat %6 : i32 -> tensor<64xi32>
    %8 = arith.addi %7, %3 : tensor<64xi32>
    %9 = arith.muli %arg3, %arg4 : i32
    %10 = tt.splat %9 : i32 -> tensor<64xi32>
    %11 = arith.cmpi slt, %5, %10 : tensor<64xi32>
    %12 = tt.splat %arg5 : i32 -> tensor<64xi32>
    %13 = arith.cmpi slt, %8, %12 : tensor<64xi32>
    %14 = tt.expand_dims %11 {axis = 1 : i32} : tensor<64xi1> -> tensor<64x1xi1>
    %15 = tt.broadcast %14 : tensor<64x1xi1> -> tensor<64x64xi1>
    %16 = tt.expand_dims %13 {axis = 0 : i32} : tensor<64xi1> -> tensor<1x64xi1>
    %17 = tt.broadcast %16 : tensor<1x64xi1> -> tensor<64x64xi1>
    %18 = arith.andi %15, %17 : tensor<64x64xi1>
    %19 = arith.divsi %5, %10 : tensor<64xi32>
    %20 = arith.remsi %5, %10 : tensor<64xi32>
    %21 = tt.splat %arg4 : i32 -> tensor<64xi32>
    %22 = arith.divsi %20, %21 : tensor<64xi32>
    %23 = arith.remsi %20, %21 : tensor<64xi32>
    %24 = scf.for %arg16 = %c0_i32 to %arg6 step %c1_i32 iter_args(%arg17 = %cst) -> (tensor<64x64xf32>)  : i32 {
      %40 = tt.splat %arg7 : i32 -> tensor<64xi32>
      %41 = arith.muli %19, %40 : tensor<64xi32>
      %42 = tt.splat %arg8 : i32 -> tensor<64xi32>
      %43 = arith.muli %22, %42 : tensor<64xi32>
      %44 = arith.addi %41, %43 : tensor<64xi32>
      %45 = tt.splat %arg9 : i32 -> tensor<64xi32>
      %46 = arith.muli %23, %45 : tensor<64xi32>
      %47 = arith.addi %44, %46 : tensor<64xi32>
      %48 = tt.splat %arg16 : i32 -> tensor<64xi32>
      %49 = arith.addi %47, %48 : tensor<64xi32>
      %50 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<64x!tt.ptr<f32>>
      %51 = tt.addptr %50, %49 : tensor<64x!tt.ptr<f32>>, tensor<64xi32>
      %52 = tt.load %51, %11, %cst_0 : tensor<64x!tt.ptr<f32>>
      %53 = tt.splat %arg10 : i32 -> tensor<64xi32>
      %54 = arith.muli %22, %53 : tensor<64xi32>
      %55 = tt.splat %arg11 : i32 -> tensor<64xi32>
      %56 = arith.muli %23, %55 : tensor<64xi32>
      %57 = arith.addi %54, %56 : tensor<64xi32>
      %58 = arith.addi %57, %48 : tensor<64xi32>
      %59 = tt.expand_dims %58 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32>
      %60 = tt.expand_dims %8 {axis = 0 : i32} : tensor<64xi32> -> tensor<1x64xi32>
      %61 = tt.splat %arg12 : i32 -> tensor<1x64xi32>
      %62 = arith.muli %60, %61 : tensor<1x64xi32>
      %63 = tt.broadcast %59 : tensor<64x1xi32> -> tensor<64x64xi32>
      %64 = tt.broadcast %62 : tensor<1x64xi32> -> tensor<64x64xi32>
      %65 = arith.addi %63, %64 : tensor<64x64xi32>
      %66 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<64x64x!tt.ptr<f32>>
      %67 = tt.addptr %66, %65 : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
      %68 = tt.load %67, %18, %cst : tensor<64x64x!tt.ptr<f32>>
      %69 = tt.expand_dims %52 {axis = 1 : i32} : tensor<64xf32> -> tensor<64x1xf32>
      %70 = tt.broadcast %69 : tensor<64x1xf32> -> tensor<64x64xf32>
      %71 = arith.mulf %70, %68 : tensor<64x64xf32>
      %72 = arith.addf %arg17, %71 : tensor<64x64xf32>
      scf.yield %72 : tensor<64x64xf32>
    }
    %25 = tt.splat %arg13 : i32 -> tensor<64xi32>
    %26 = arith.muli %19, %25 : tensor<64xi32>
    %27 = tt.splat %arg14 : i32 -> tensor<64xi32>
    %28 = arith.muli %22, %27 : tensor<64xi32>
    %29 = arith.addi %26, %28 : tensor<64xi32>
    %30 = tt.splat %arg15 : i32 -> tensor<64xi32>
    %31 = arith.muli %23, %30 : tensor<64xi32>
    %32 = arith.addi %29, %31 : tensor<64xi32>
    %33 = tt.expand_dims %32 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32>
    %34 = tt.expand_dims %8 {axis = 0 : i32} : tensor<64xi32> -> tensor<1x64xi32>
    %35 = tt.broadcast %33 : tensor<64x1xi32> -> tensor<64x64xi32>
    %36 = tt.broadcast %34 : tensor<1x64xi32> -> tensor<64x64xi32>
    %37 = arith.addi %35, %36 : tensor<64x64xi32>
    %38 = tt.splat %arg2 : !tt.ptr<f32> -> tensor<64x64x!tt.ptr<f32>>
    %39 = tt.addptr %38, %37 : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
    tt.store %39, %24, %18 : tensor<64x64x!tt.ptr<f32>>
    tt.return
  }
}
