// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// RUN: triton-shared-opt --triton-to-linalg-experimental --cse %s | FileCheck %s

// RUN: triton-shared-opt --triton-to-linalg-experimental="enable-make-gather-scatter=false" %s | FileCheck %s --check-prefix=NO_GATHER

// Make sure no extract_slice when enable-make-gather-scatter=false..
// NO_GATHER-LABLE: func.func @row_gather2(
// NO_GATHER-NOT: extract_slice


// Make sure extract_slice is generated correctly.

// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0, d1) -> (d0, d1)>

// CHECK-LABEL:   func.func @row_gather2(
// CHECK-SAME:                           %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                           %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                           %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:                           %[[ARG13:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG14:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG15:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG16:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG17:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                           %[[ARG18:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[VAL_0:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_1:.*]] = arith.constant 8 : i32
// CHECK:           %[[VAL_2:.*]] = arith.constant 16 : index
// CHECK:           %[[VAL_3:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_4:.*]] = tensor.empty() : tensor<16x1xi32>
// CHECK:           %[[VAL_5:.*]] = tensor.collapse_shape %[[VAL_4]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           %[[VAL_6:.*]] = linalg.fill ins(%[[VAL_1]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_7:.*]] = tensor.expand_shape %[[VAL_6]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_8:.*]] = arith.muli %[[ARG5]], %[[VAL_1]] : i32
// CHECK:           %[[VAL_9:.*]] = tensor.empty() : tensor<16xi32>
// CHECK:           %[[VAL_10:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_9]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_11:.*]]: i32):
// CHECK:             %[[VAL_12:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_13:.*]] = arith.index_cast %[[VAL_12]] : index to i32
// CHECK:             linalg.yield %[[VAL_13]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_14:.*]] = tensor.expand_shape %[[VAL_10]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_15:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_14]], %[[VAL_7]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_14]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_16:.*]]: i32, %[[VAL_17:.*]]: i32, %[[VAL_18:.*]]: i32):
// CHECK:             %[[VAL_19:.*]] = arith.remsi %[[VAL_16]], %[[VAL_17]] : i32
// CHECK:             linalg.yield %[[VAL_19]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_20:.*]] = arith.muli %[[ARG3]], %[[VAL_1]] : i32
// CHECK:           %[[VAL_21:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_14]], %[[VAL_7]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_14]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_22:.*]]: i32, %[[VAL_23:.*]]: i32, %[[VAL_24:.*]]: i32):
// CHECK:             %[[VAL_25:.*]] = arith.divsi %[[VAL_22]], %[[VAL_23]] : i32
// CHECK:             linalg.yield %[[VAL_25]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_26:.*]] = arith.extsi %[[ARG2]] : i32 to i64
// CHECK:           %[[VAL_27:.*]] = arith.muli %[[VAL_26]], %[[ARG7]] : i64
// CHECK:           %[[VAL_28:.*]] = arith.index_cast %[[VAL_27]] : i64 to index
// CHECK:           %[[VAL_29:.*]] = arith.index_cast %[[ARG8]] : i64 to index
// CHECK:           %[[VAL_30:.*]] = linalg.fill ins(%[[ARG4]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_31:.*]] = tensor.expand_shape %[[VAL_30]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_32:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_21]], %[[VAL_31]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_21]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_33:.*]]: i32, %[[VAL_34:.*]]: i32, %[[VAL_35:.*]]: i32):
// CHECK:             %[[VAL_36:.*]] = arith.addi %[[VAL_33]], %[[VAL_34]] : i32
// CHECK:             linalg.yield %[[VAL_36]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_37:.*]] = arith.index_cast %[[ARG6]] : i64 to index
// CHECK:           %[[VAL_38:.*]] = linalg.fill ins(%[[VAL_20]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_39:.*]] = tensor.expand_shape %[[VAL_38]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_40:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_15]], %[[VAL_39]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_15]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_41:.*]]: i32, %[[VAL_42:.*]]: i32, %[[VAL_43:.*]]: i32):
// CHECK:             %[[VAL_44:.*]] = arith.addi %[[VAL_41]], %[[VAL_42]] : i32
// CHECK:             linalg.yield %[[VAL_44]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_45:.*]] = arith.index_cast %[[VAL_37]] : index to i32
// CHECK:           %[[VAL_46:.*]] = linalg.fill ins(%[[VAL_45]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_47:.*]] = tensor.expand_shape %[[VAL_46]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_48:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_32]], %[[VAL_47]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_32]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_49:.*]]: i32, %[[VAL_50:.*]]: i32, %[[VAL_51:.*]]: i32):
// CHECK:             %[[VAL_52:.*]] = arith.muli %[[VAL_49]], %[[VAL_50]] : i32
// CHECK:             linalg.yield %[[VAL_52]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_53:.*]] = arith.index_cast %[[VAL_29]] : index to i32
// CHECK:           %[[VAL_54:.*]] = linalg.fill ins(%[[VAL_53]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_55:.*]] = tensor.expand_shape %[[VAL_54]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_56:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_40]], %[[VAL_55]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_40]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_57:.*]]: i32, %[[VAL_58:.*]]: i32, %[[VAL_59:.*]]: i32):
// CHECK:             %[[VAL_60:.*]] = arith.muli %[[VAL_57]], %[[VAL_58]] : i32
// CHECK:             linalg.yield %[[VAL_60]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_61:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_48]], %[[VAL_56]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_48]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_62:.*]]: i32, %[[VAL_63:.*]]: i32, %[[VAL_64:.*]]: i32):
// CHECK:             %[[VAL_65:.*]] = arith.addi %[[VAL_62]], %[[VAL_63]] : i32
// CHECK:             linalg.yield %[[VAL_65]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_66:.*]] = arith.index_cast %[[VAL_28]] : index to i32
// CHECK:           %[[VAL_67:.*]] = linalg.fill ins(%[[VAL_66]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_68:.*]] = tensor.expand_shape %[[VAL_67]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_69:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_68]], %[[VAL_61]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_68]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_70:.*]]: i32, %[[VAL_71:.*]]: i32, %[[VAL_72:.*]]: i32):
// CHECK:             %[[VAL_73:.*]] = arith.addi %[[VAL_70]], %[[VAL_71]] : i32
// CHECK:             linalg.yield %[[VAL_73]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_74:.*]] = tensor.collapse_shape %[[VAL_69]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           %[[VAL_75:.*]] = arith.index_cast %[[VAL_8]] : i32 to index
// CHECK:           %[[VAL_76:.*]] = arith.minsi %[[VAL_75]], %[[VAL_2]] : index
// CHECK:           %[[VAL_77:.*]] = arith.maxsi %[[VAL_76]], %[[VAL_3]] : index
// CHECK:           %[[VAL_78:.*]] = arith.minsi %[[VAL_77]], %[[VAL_2]] : index
// CHECK:           %[[VAL_79:.*]] = memref.alloc() : memref<16x16xf32>
// CHECK:           %[[VAL_80:.*]] = arith.minsi %[[VAL_78]], %[[VAL_2]] : index
// CHECK:           scf.for %[[VAL_81:.*]] = %[[VAL_3]] to %[[VAL_80]] step %[[VAL_0]] {
// CHECK:             %[[VAL_82:.*]] = tensor.extract %[[VAL_74]]{{\[}}%[[VAL_81]]] : tensor<16xi32>
// CHECK:             %[[VAL_83:.*]] = arith.index_cast %[[VAL_82]] : i32 to index
// CHECK:             %[[VAL_84:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: {{\[}}%[[VAL_83]]], sizes: [1, 16], strides: [1, 1] : memref<*xf32> to memref<1x16xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_85:.*]] = memref.subview %[[VAL_84]][0, 0] [1, 8] [1, 1] : memref<1x16xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_86:.*]] = memref.subview %[[VAL_79]]{{\[}}%[[VAL_81]], 0] [1, 8] [1, 1] : memref<16x16xf32> to memref<1x8xf32, strided<[16, 1], offset: ?>>
// CHECK:             memref.copy %[[VAL_85]], %[[VAL_86]] : memref<1x8xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[16, 1], offset: ?>>
// CHECK:           }
// CHECK:           %[[VAL_87:.*]] = bufferization.to_tensor %[[VAL_79]] restrict writable : memref<16x16xf32> to tensor<16x16xf32>
// CHECK:           %[[VAL_88:.*]] = arith.muli %[[VAL_26]], %[[ARG10]] : i64
// CHECK:           %[[VAL_89:.*]] = arith.extsi %[[ARG18]] : i32 to i64
// CHECK:           %[[VAL_90:.*]] = arith.muli %[[VAL_89]], %[[ARG12]] : i64
// CHECK:           %[[VAL_91:.*]] = arith.addi %[[VAL_88]], %[[VAL_90]] : i64
// CHECK:           %[[VAL_92:.*]] = arith.index_cast %[[VAL_91]] : i64 to index
// CHECK:           %[[VAL_93:.*]] = arith.index_cast %[[ARG11]] : i64 to index
// CHECK:           %[[VAL_94:.*]] = arith.index_cast %[[ARG9]] : i64 to index
// CHECK:           %[[VAL_95:.*]] = arith.index_cast %[[VAL_94]] : index to i32
// CHECK:           %[[VAL_96:.*]] = linalg.fill ins(%[[VAL_95]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_97:.*]] = tensor.expand_shape %[[VAL_96]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_98:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_32]], %[[VAL_97]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_32]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_99:.*]]: i32, %[[VAL_100:.*]]: i32, %[[VAL_101:.*]]: i32):
// CHECK:             %[[VAL_102:.*]] = arith.muli %[[VAL_99]], %[[VAL_100]] : i32
// CHECK:             linalg.yield %[[VAL_102]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_103:.*]] = arith.index_cast %[[VAL_93]] : index to i32
// CHECK:           %[[VAL_104:.*]] = linalg.fill ins(%[[VAL_103]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_105:.*]] = tensor.expand_shape %[[VAL_104]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_106:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_40]], %[[VAL_105]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_40]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_107:.*]]: i32, %[[VAL_108:.*]]: i32, %[[VAL_109:.*]]: i32):
// CHECK:             %[[VAL_110:.*]] = arith.muli %[[VAL_107]], %[[VAL_108]] : i32
// CHECK:             linalg.yield %[[VAL_110]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_111:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_98]], %[[VAL_106]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_98]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_112:.*]]: i32, %[[VAL_113:.*]]: i32, %[[VAL_114:.*]]: i32):
// CHECK:             %[[VAL_115:.*]] = arith.addi %[[VAL_112]], %[[VAL_113]] : i32
// CHECK:             linalg.yield %[[VAL_115]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_116:.*]] = arith.index_cast %[[VAL_92]] : index to i32
// CHECK:           %[[VAL_117:.*]] = linalg.fill ins(%[[VAL_116]] : i32) outs(%[[VAL_5]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK:           %[[VAL_118:.*]] = tensor.expand_shape %[[VAL_117]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[VAL_119:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_118]], %[[VAL_111]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[VAL_118]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_120:.*]]: i32, %[[VAL_121:.*]]: i32, %[[VAL_122:.*]]: i32):
// CHECK:             %[[VAL_123:.*]] = arith.addi %[[VAL_120]], %[[VAL_121]] : i32
// CHECK:             linalg.yield %[[VAL_123]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[VAL_124:.*]] = tensor.collapse_shape %[[VAL_119]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           scf.for %[[VAL_125:.*]] = %[[VAL_3]] to %[[VAL_80]] step %[[VAL_0]] {
// CHECK:             %[[VAL_126:.*]] = tensor.extract %[[VAL_124]]{{\[}}%[[VAL_125]]] : tensor<16xi32>
// CHECK:             %[[VAL_127:.*]] = arith.index_cast %[[VAL_126]] : i32 to index
// CHECK:             %[[VAL_128:.*]] = tensor.extract_slice %[[VAL_87]]{{\[}}%[[VAL_125]], 0] [1, 8] [1, 1] : tensor<16x16xf32> to tensor<1x8xf32>
// CHECK:             %[[VAL_129:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: {{\[}}%[[VAL_127]]], sizes: [1, 16], strides: [1, 1] : memref<*xf32> to memref<1x16xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_130:.*]] = memref.subview %[[VAL_129]][0, 0] [1, 8] [1, 1] : memref<1x16xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[VAL_131:.*]] = memref.cast %[[VAL_130]] : memref<1x8xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[?, ?], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[VAL_128]] in writable %[[VAL_131]] : (tensor<1x8xf32>, memref<1x8xf32, strided<[?, ?], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           return

module {
  tt.func public @row_gather2(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i32, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i64, %arg7: i64, %arg8: i64, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<1x16xi32>
    %cst_0 = arith.constant dense<8> : tensor<16x1xi32>
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.get_program_id z : i32
    %1 = arith.muli %arg5, %c8_i32 : i32
    %2 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %3 = tt.expand_dims %2 {axis = 1 : i32} : tensor<16xi32> -> tensor<16x1xi32>
    %4 = arith.remsi %3, %cst_0 : tensor<16x1xi32>
    %5 = arith.muli %arg3, %c8_i32 : i32
    %6 = tt.splat %5 : i32 -> tensor<16x1xi32>
    %7 = arith.addi %4, %6 : tensor<16x1xi32>
    %8 = arith.divsi %3, %cst_0 : tensor<16x1xi32>
    %9 = tt.splat %arg4 : i32 -> tensor<16x1xi32>
    %10 = arith.addi %8, %9 : tensor<16x1xi32>
    %11 = arith.extsi %arg2 : i32 to i64
    %12 = arith.muli %11, %arg7 : i64
    %13 = tt.addptr %arg0, %12 : !tt.ptr<f32>, i64
    %14 = arith.extsi %10 : tensor<16x1xi32> to tensor<16x1xi64>
    %15 = tt.splat %arg6 : i64 -> tensor<16x1xi64>
    %16 = arith.muli %14, %15 : tensor<16x1xi64>
    %17 = tt.splat %13 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %18 = arith.extsi %7 : tensor<16x1xi32> to tensor<16x1xi64>
    %19 = tt.splat %arg8 : i64 -> tensor<16x1xi64>
    %20 = arith.muli %18, %19 : tensor<16x1xi64>
    %21 = arith.addi %16, %20 : tensor<16x1xi64>
    %22 = tt.addptr %17, %21 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %23 = tt.expand_dims %2 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %24 = tt.broadcast %22 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %25 = tt.broadcast %23 : tensor<1x16xi32> -> tensor<16x16xi32>
    %26 = tt.addptr %24, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    %27 = arith.cmpi slt, %23, %cst : tensor<1x16xi32>
    %28 = tt.splat %1 : i32 -> tensor<16x1xi32>
    %29 = arith.cmpi slt, %3, %28 : tensor<16x1xi32>
    %30 = tt.broadcast %27 : tensor<1x16xi1> -> tensor<16x16xi1>
    %31 = tt.broadcast %29 : tensor<16x1xi1> -> tensor<16x16xi1>
    %32 = arith.andi %30, %31 : tensor<16x16xi1>
    %33 = tt.load %26, %32 : tensor<16x16x!tt.ptr<f32>>
    %34 = arith.muli %11, %arg10 : i64
    %35 = arith.extsi %0 : i32 to i64
    %36 = arith.muli %35, %arg12 : i64
    %37 = arith.addi %34, %36 : i64
    %38 = tt.addptr %arg1, %37 : !tt.ptr<f32>, i64
    %39 = tt.splat %arg9 : i64 -> tensor<16x1xi64>
    %40 = arith.muli %14, %39 : tensor<16x1xi64>
    %41 = tt.splat %38 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %42 = tt.splat %arg11 : i64 -> tensor<16x1xi64>
    %43 = arith.muli %18, %42 : tensor<16x1xi64>
    %44 = arith.addi %40, %43 : tensor<16x1xi64>
    %45 = tt.addptr %41, %44 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %46 = tt.broadcast %45 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %47 = tt.addptr %46, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    tt.store %47, %33, %32 : tensor<16x16x!tt.ptr<f32>>
    tt.return
  }
}
