// RUN: triton-shared-opt --tptr-to-llvm %s | FileCheck %s

#loc = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0)
#loc7 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":323:7)
module {
  func.func @simple_cf_into_structured_load_2(%arg0: memref<*xi64> {tt.divisibility = 16 : i32} loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg1: memref<*xi64> {tt.divisibility = 16 : i32} loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg2: memref<*xf32> {tt.divisibility = 16 : i32} loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg3: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg4: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg5: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg6: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg7: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0), %arg8: i32 loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":316:0)) {
    %0 = tptr.type_offset f32  : i32 loc(#loc1)
    %c0 = arith.constant 0 : index loc(#loc1)
    %1 = tptr.type_offset i64  : i32 loc(#loc1)
    %c3_i32 = arith.constant 3 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %cast = memref.cast %arg2 : memref<*xf32> to memref<1xf32> loc(#loc2)
    %2 = tptr.from_memref %cast : memref<1xf32> to <#tptr.default_memory_space> loc(#loc2)
    %cast_0 = memref.cast %arg1 : memref<*xi64> to memref<1xi64> loc(#loc3)
    %3 = tptr.from_memref %cast_0 : memref<1xi64> to <#tptr.default_memory_space> loc(#loc3)
    %cast_1 = memref.cast %arg0 : memref<*xi64> to memref<1xi64> loc(#loc4)
    %4 = tptr.from_memref %cast_1 : memref<1xi64> to <#tptr.default_memory_space> loc(#loc4)
    %5 = arith.remsi %arg6, %c2_i32 : i32 loc(#loc5)
    %6 = arith.cmpi eq, %5, %c0_i32 : i32 loc(#loc6)
    cf.cond_br %6, ^bb1, ^bb2 loc(#loc7)
  ^bb1:  // pred: ^bb0
    %7 = arith.muli %c2_i32, %1 : i32 loc(#loc4)
    %8 = tptr.ptradd %4 %7 : <#tptr.default_memory_space>, i32 to <#tptr.default_memory_space> loc(#loc4)
    cf.br ^bb3(%8 : !ptr.ptr<#tptr.default_memory_space>) loc(#loc7)
  ^bb2:  // pred: ^bb0
    %9 = arith.muli %c3_i32, %1 : i32 loc(#loc3)
    %10 = tptr.ptradd %3 %9 : <#tptr.default_memory_space>, i32 to <#tptr.default_memory_space> loc(#loc3)
    cf.br ^bb3(%10 : !ptr.ptr<#tptr.default_memory_space>) loc(#loc7)
  ^bb3(%11: !ptr.ptr<#tptr.default_memory_space> loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":323:7)):  // 2 preds: ^bb1, ^bb2
    cf.br ^bb4 loc(#loc7)
  ^bb4:  // pred: ^bb3
    %12 = arith.muli %arg6, %1 : i32 loc(#loc8)
    %13 = tptr.ptradd %11 %12 : <#tptr.default_memory_space>, i32 to <#tptr.default_memory_space> loc(#loc8)
    %14 = tptr.to_memref %13 : <#tptr.default_memory_space> to memref<1xi64> loc(#loc9)
    %15 = memref.load %14[%c0] : memref<1xi64> loc(#loc9)
    %16 = arith.muli %arg6, %0 : i32 loc(#loc2)
    %17 = tptr.ptradd %2 %16 : <#tptr.default_memory_space>, i32 to <#tptr.default_memory_space> loc(#loc2)
    %18 = arith.sitofp %15 : i64 to f32 loc(#loc10)
    %19 = tptr.to_memref %17 : <#tptr.default_memory_space> to memref<1xf32> loc(#loc10)
    memref.store %18, %19[%c0] : memref<1xf32> loc(#loc10)
    return loc(#loc)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":329:23)
#loc3 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":326:24)
#loc4 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":324:24)
#loc5 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":318:23)
#loc6 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":318:28)
#loc8 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":328:27)
#loc9 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":328:21)
#loc10 = loc("/data03/yanxitan/yanxi-doing/from_nhat/test_ptr.py":329:28)

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



// CHECK-LABEL:   func.func @simple_cf_into_structured_load_2(
// CHECK-SAME:  %[[VAL_0:.*]]: memref<*xi64> {tt.divisibility = 16 : i32}, %[[VAL_1:.*]]: memref<*xi64> {tt.divisibility = 16 : i32}, %[[VAL_2:.*]]: memref<*xf32> {tt.divisibility = 16 : i32}, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK:           %[[VAL_9:.*]] = llvm.mlir.constant(1 : i64) : i64
// CHECK:           %[[VAL_10:.*]] = llvm.mlir.constant(0 : i64) : i64
// CHECK:           %[[VAL_11:.*]] = llvm.mlir.undef : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_12:.*]] = llvm.mlir.constant(4 : i32) : i32
// CHECK:           %[[VAL_13:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_14:.*]] = llvm.mlir.constant(8 : i32) : i32
// CHECK:           %[[VAL_15:.*]] = arith.constant 3 : i32
// CHECK:           %[[VAL_16:.*]] = arith.constant 2 : i32
// CHECK:           %[[VAL_17:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_18:.*]] = memref.cast %[[VAL_2]] : memref<*xf32> to memref<1xf32>
// CHECK:           %[[VAL_19:.*]] = builtin.unrealized_conversion_cast %[[VAL_18]] : memref<1xf32> to !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_20:.*]] = llvm.extractvalue %[[VAL_19]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_21:.*]] = memref.cast %[[VAL_1]] : memref<*xi64> to memref<1xi64>
// CHECK:           %[[VAL_22:.*]] = builtin.unrealized_conversion_cast %[[VAL_21]] : memref<1xi64> to !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_23:.*]] = llvm.extractvalue %[[VAL_22]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_24:.*]] = memref.cast %[[VAL_0]] : memref<*xi64> to memref<1xi64>
// CHECK:           %[[VAL_25:.*]] = builtin.unrealized_conversion_cast %[[VAL_24]] : memref<1xi64> to !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_26:.*]] = llvm.extractvalue %[[VAL_25]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_27:.*]] = arith.remsi %[[VAL_6]], %[[VAL_16]] : i32
// CHECK:           %[[VAL_28:.*]] = arith.cmpi eq, %[[VAL_27]], %[[VAL_17]] : i32
// CHECK:           %[[VAL_29:.*]] = arith.select %[[VAL_28]], %[[VAL_16]], %[[VAL_15]] : i32
// CHECK:           %[[VAL_30:.*]] = arith.select %[[VAL_28]], %[[VAL_26]], %[[VAL_23]] : !llvm.ptr
// CHECK:           %[[VAL_31:.*]] = arith.muli %[[VAL_29]], %[[VAL_14]] : i32
// CHECK:           %[[VAL_32:.*]] = llvm.getelementptr %[[VAL_30]]{{\[}}%[[VAL_31]]] : (!llvm.ptr, i32) -> !llvm.ptr, i8
// CHECK:           %[[VAL_33:.*]] = arith.muli %[[VAL_6]], %[[VAL_14]] : i32
// CHECK:           %[[VAL_34:.*]] = llvm.getelementptr %[[VAL_32]]{{\[}}%[[VAL_33]]] : (!llvm.ptr, i32) -> !llvm.ptr, i8
// CHECK:           %[[VAL_35:.*]] = llvm.insertvalue %[[VAL_34]], %[[VAL_11]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_36:.*]] = llvm.insertvalue %[[VAL_34]], %[[VAL_35]][1] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_37:.*]] = llvm.insertvalue %[[VAL_10]], %[[VAL_36]][2] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_38:.*]] = llvm.insertvalue %[[VAL_9]], %[[VAL_37]][3, 0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_39:.*]] = llvm.insertvalue %[[VAL_9]], %[[VAL_38]][4, 0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_40:.*]] = builtin.unrealized_conversion_cast %[[VAL_39]] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)> to memref<1xi64>
// CHECK:           %[[VAL_41:.*]] = memref.load %[[VAL_40]]{{\[}}%[[VAL_13]]] : memref<1xi64>
// CHECK:           %[[VAL_42:.*]] = arith.muli %[[VAL_6]], %[[VAL_12]] : i32
// CHECK:           %[[VAL_43:.*]] = llvm.getelementptr %[[VAL_20]]{{\[}}%[[VAL_42]]] : (!llvm.ptr, i32) -> !llvm.ptr, i8
// CHECK:           %[[VAL_44:.*]] = arith.sitofp %[[VAL_41]] : i64 to f32
// CHECK:           %[[VAL_45:.*]] = llvm.insertvalue %[[VAL_43]], %[[VAL_11]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_46:.*]] = llvm.insertvalue %[[VAL_43]], %[[VAL_45]][1] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_47:.*]] = llvm.insertvalue %[[VAL_10]], %[[VAL_46]][2] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_48:.*]] = llvm.insertvalue %[[VAL_9]], %[[VAL_47]][3, 0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_49:.*]] = llvm.insertvalue %[[VAL_9]], %[[VAL_48]][4, 0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_50:.*]] = builtin.unrealized_conversion_cast %[[VAL_49]] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)> to memref<1xf32>
// CHECK:           memref.store %[[VAL_44]], %[[VAL_50]]{{\[}}%[[VAL_13]]] : memref<1xf32>
// CHECK:           return
// CHECK:         }

