// RUN: triton-shared-opt --tptr-to-llvm %s | FileCheck %s

module {
  llvm.func @simple_cf_ptradd(%arg0: i64, %arg1: !llvm.ptr, %arg2: i64, %arg3: !llvm.ptr, %arg4: i64, %arg5: !llvm.ptr, %arg6: i32, %arg7: i32, %arg8: i32, %arg9: i32, %arg10: i32, %arg11: i32) {
    %0 = llvm.mlir.poison : !llvm.struct<(i64, ptr)>
    %1 = llvm.insertvalue %arg4, %0[0] : !llvm.struct<(i64, ptr)>
    %2 = llvm.insertvalue %arg5, %1[1] : !llvm.struct<(i64, ptr)>
    %3 = builtin.unrealized_conversion_cast %2 : !llvm.struct<(i64, ptr)> to memref<*xf32>
    %4 = llvm.mlir.poison : !llvm.struct<(i64, ptr)>
    %5 = llvm.insertvalue %arg2, %4[0] : !llvm.struct<(i64, ptr)>
    %6 = llvm.insertvalue %arg3, %5[1] : !llvm.struct<(i64, ptr)>
    %7 = builtin.unrealized_conversion_cast %6 : !llvm.struct<(i64, ptr)> to memref<*xi64>
    %8 = llvm.mlir.poison : !llvm.struct<(i64, ptr)>
    %9 = llvm.insertvalue %arg0, %8[0] : !llvm.struct<(i64, ptr)>
    %10 = llvm.insertvalue %arg1, %9[1] : !llvm.struct<(i64, ptr)>
    %11 = builtin.unrealized_conversion_cast %10 : !llvm.struct<(i64, ptr)> to memref<*xi64>
    %12 = builtin.unrealized_conversion_cast %11 : memref<*xi64> to !llvm.struct<(i64, ptr)>
    %13 = builtin.unrealized_conversion_cast %7 : memref<*xi64> to !llvm.struct<(i64, ptr)>
    %14 = builtin.unrealized_conversion_cast %3 : memref<*xf32> to !llvm.struct<(i64, ptr)>
    %15 = llvm.mlir.constant(0 : i32) : i32
    %16 = llvm.mlir.constant(2 : i32) : i32
    %17 = llvm.mlir.constant(3 : i32) : i32
    %18 = llvm.mlir.constant(0 : index) : i64
    %19 = llvm.extractvalue %14[1] : !llvm.struct<(i64, ptr)>
    %20 = llvm.load %19 : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %21 = builtin.unrealized_conversion_cast %20 : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)> to memref<1xf32>
    %22 = tptr.from_memref %21 : memref<1xf32> to !tt.ptr<f32>
    %23 = llvm.extractvalue %13[1] : !llvm.struct<(i64, ptr)>
    %24 = llvm.load %23 : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %25 = builtin.unrealized_conversion_cast %24 : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)> to memref<1xi64>
    %26 = tptr.from_memref %25 : memref<1xi64> to !tt.ptr<i64>
    %27 = llvm.extractvalue %12[1] : !llvm.struct<(i64, ptr)>
    %28 = llvm.load %27 : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %29 = builtin.unrealized_conversion_cast %28 : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)> to memref<1xi64>
    %30 = tptr.from_memref %29 : memref<1xi64> to !tt.ptr<i64>
    %31 = llvm.srem %arg9, %16 : i32
    %32 = llvm.icmp "eq" %31, %15 : i32
    cf.cond_br %32, ^bb1(%30, %16 : !tt.ptr<i64>, i32), ^bb1(%26, %17 : !tt.ptr<i64>, i32)
  ^bb1(%33: !tt.ptr<i64>, %34: i32):  // 2 preds: ^bb0, ^bb0
    %35 = tptr.ptradd %33 %34 : !tt.ptr<i64>, i32 to !tt.ptr<i64>
    cf.br ^bb2
  ^bb2:  // pred: ^bb1
    cf.br ^bb3
  ^bb3:  // pred: ^bb2
    %36 = tptr.ptradd %35 %arg9 : !tt.ptr<i64>, i32 to !tt.ptr<i64>
    %37 = tptr.to_memref %36 : !tt.ptr<i64> to memref<1xi64>
    %38 = builtin.unrealized_conversion_cast %37 : memref<1xi64> to !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %39 = llvm.extractvalue %38[1] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %40 = llvm.getelementptr inbounds|nuw %39[%18] : (!llvm.ptr, i64) -> !llvm.ptr, i64
    %41 = llvm.load %40 : !llvm.ptr -> i64
    %42 = tptr.ptradd %22 %arg9 : !tt.ptr<f32>, i32 to !tt.ptr<f32>
    %43 = llvm.sitofp %41 : i64 to f32
    %44 = tptr.to_memref %42 : !tt.ptr<f32> to memref<1xf32>
    %45 = builtin.unrealized_conversion_cast %44 : memref<1xf32> to !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %46 = llvm.extractvalue %45[1] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
    %47 = llvm.getelementptr inbounds|nuw %46[%18] : (!llvm.ptr, i64) -> !llvm.ptr, f32
    llvm.store %43, %47 : f32, !llvm.ptr
    llvm.return
  }
}


// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK-LABEL:   llvm.func @simple_cf_ptradd(
// CHECK-SAME:  %[[VAL_0:.*]]: i64, %[[VAL_1:.*]]: !llvm.ptr, %[[VAL_2:.*]]: i64, %[[VAL_3:.*]]: !llvm.ptr, %[[VAL_4:.*]]: i64, %[[VAL_5:.*]]: !llvm.ptr, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32, %[[VAL_9:.*]]: i32, %[[VAL_10:.*]]: i32, %[[VAL_11:.*]]: i32) {
// CHECK:           %[[VAL_12:.*]] = llvm.mlir.constant(3 : i32) : i32
// CHECK:           %[[VAL_13:.*]] = llvm.mlir.constant(2 : i32) : i32
// CHECK:           %[[VAL_14:.*]] = llvm.mlir.constant(0 : i32) : i32
// CHECK:           %[[VAL_15:.*]] = llvm.load %[[VAL_5]] : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_16:.*]] = llvm.extractvalue %[[VAL_15]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_17:.*]] = llvm.load %[[VAL_3]] : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_18:.*]] = llvm.extractvalue %[[VAL_17]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_19:.*]] = llvm.load %[[VAL_1]] : !llvm.ptr -> !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_20:.*]] = llvm.extractvalue %[[VAL_19]][0] : !llvm.struct<(ptr, ptr, i64, array<1 x i64>, array<1 x i64>)>
// CHECK:           %[[VAL_21:.*]] = llvm.srem %[[VAL_9]], %[[VAL_13]] : i32
// CHECK:           %[[VAL_22:.*]] = llvm.icmp "eq" %[[VAL_21]], %[[VAL_14]] : i32
// CHECK:           %[[VAL_23:.*]] = arith.select %[[VAL_22]], %[[VAL_20]], %[[VAL_18]] : !llvm.ptr
// CHECK:           %[[VAL_24:.*]] = arith.select %[[VAL_22]], %[[VAL_13]], %[[VAL_12]] : i32
// CHECK:           %[[VAL_25:.*]] = llvm.getelementptr %[[VAL_23]]{{\[}}%[[VAL_24]]] : (!llvm.ptr, i32) -> !llvm.ptr, i64
// CHECK:           %[[VAL_26:.*]] = llvm.getelementptr %[[VAL_25]]{{\[}}%[[VAL_9]]] : (!llvm.ptr, i32) -> !llvm.ptr, i64
// CHECK:           %[[VAL_27:.*]] = llvm.load %[[VAL_26]] : !llvm.ptr -> i64
// CHECK:           %[[VAL_28:.*]] = llvm.getelementptr %[[VAL_16]]{{\[}}%[[VAL_9]]] : (!llvm.ptr, i32) -> !llvm.ptr, f32
// CHECK:           %[[VAL_29:.*]] = llvm.sitofp %[[VAL_27]] : i64 to f32
// CHECK:           llvm.store %[[VAL_29]], %[[VAL_28]] : f32, !llvm.ptr
// CHECK:           llvm.return
// CHECK:         }

