// RUN: triton-shared-opt --triton-arith-to-linalg="tensor-ptr-to-linalg" --triton-to-ptr --cse --canonicalize %s | FileCheck %s

module {
  tt.func public @cast_with_int_ptr(%arg0: !tt.ptr<i32>, %arg1: !tt.ptr<i32>, %arg2: i32) attributes {noinline = false} {
    %c4_i32 = arith.constant 4 : i32
    %c3_i32 = arith.constant 3 : i32
    %c2_i32 = arith.constant 2 : i32
    %c1_i32 = arith.constant 1 : i32
    %c10_i64 = arith.constant 10 : i64
    %c9_i32 = arith.constant 9 : i32
    %c10_i32 = arith.constant 10 : i32
    %c111_i32 = arith.constant 111 : i32
    %0 = tt.addptr %arg0, %c111_i32 : !tt.ptr<i32>, i32
    %1 = tt.bitcast %0 : !tt.ptr<i32> -> !tt.ptr<i8>
    %2 = tt.addptr %1, %c10_i32 : !tt.ptr<i8>, i32
    %3 = tt.bitcast %2 : !tt.ptr<i8> -> !tt.ptr<i32>
    %4 = tt.ptr_to_int %arg1 : !tt.ptr<i32> -> i64
    %5 = tt.addptr %arg1, %4 : !tt.ptr<i32>, i64
    %6 = tt.addptr %5, %c9_i32 : !tt.ptr<i32>, i32
    %7 = tt.ptr_to_int %6 : !tt.ptr<i32> -> i64
    %8 = arith.remsi %7, %c10_i64 : i64
    %9 = tt.addptr %3, %c1_i32 : !tt.ptr<i32>, i32
    %10 = tt.addptr %9, %8 : !tt.ptr<i32>, i64
    %11 = tt.bitcast %10 : !tt.ptr<i32> -> !tt.ptr<i64>
    %12 = tt.addptr %11, %c2_i32 : !tt.ptr<i64>, i32
    %13 = tt.addptr %12, %arg2 : !tt.ptr<i64>, i32
    %14 = tt.addptr %13, %c3_i32 : !tt.ptr<i64>, i32
    %15 = tt.bitcast %14 : !tt.ptr<i64> -> !tt.ptr<i16>
    %16 = tt.addptr %15, %c4_i32 : !tt.ptr<i16>, i32
    %17 = tt.addptr %16, %arg2 : !tt.ptr<i16>, i32
    %18 = tt.addptr %17, %c3_i32 : !tt.ptr<i16>, i32
    %19 = tt.bitcast %18 : !tt.ptr<i16> -> !tt.ptr<i32>
    %20 = tt.load %19 : !tt.ptr<i32>
    %21 = arith.extsi %arg2 : i32 to i64
    %22 = arith.addi %8, %21 : i64
    %23 = tt.int_to_ptr %22 : i64 -> !tt.ptr<i32>
    tt.store %23, %20 : !tt.ptr<i32>
    tt.return
  }
}
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.



// CHECK-LABEL:   func.func @cast_with_int_ptr(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<i32>, %[[VAL_1:.*]]: !tt.ptr<i32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK-DAG:           %[[VAL_9:.*]] = arith.constant 0 : index
// CHECK-DAG:           %[[VAL_10:.*]] = arith.constant 4 : i32
// CHECK-DAG:           %[[VAL_11:.*]] = arith.constant 3 : i32
// CHECK-DAG:           %[[VAL_12:.*]] = arith.constant 2 : i32
// CHECK-DAG:           %[[VAL_13:.*]] = arith.constant 1 : i32
// CHECK-DAG:           %[[VAL_14:.*]] = arith.constant 10 : i64
// CHECK-DAG:           %[[VAL_15:.*]] = arith.constant 9 : i32
// CHECK-DAG:           %[[VAL_16:.*]] = arith.constant 10 : i32
// CHECK-DAG:           %[[VAL_17:.*]] = arith.constant 111 : i32
// CEHCK-NOT: separator of consecutive DAGs
// CHECK:           %[[VAL_18:.*]] = tptr.ptradd %[[VAL_0]] %[[VAL_17]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:           %[[VAL_19:.*]] = builtin.unrealized_conversion_cast %[[VAL_18]] : !tt.ptr<i32> to !tt.ptr<i8>
// CHECK:           %[[VAL_20:.*]] = tptr.ptradd %[[VAL_19]] %[[VAL_16]] : !tt.ptr<i8>, i32 to !tt.ptr<i8>
// CHECK:           %[[VAL_21:.*]] = builtin.unrealized_conversion_cast %[[VAL_20]] : !tt.ptr<i8> to !tt.ptr<i32>
// CHECK:           %[[VAL_22:.*]] = tptr.ptrtoint %[[VAL_1]] : !tt.ptr<i32> to i64
// CHECK:           %[[VAL_23:.*]] = tptr.ptradd %[[VAL_1]] %[[VAL_22]] : !tt.ptr<i32>, i64 to !tt.ptr<i32>
// CHECK:           %[[VAL_24:.*]] = tptr.ptradd %[[VAL_23]] %[[VAL_15]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:           %[[VAL_25:.*]] = tptr.ptrtoint %[[VAL_24]] : !tt.ptr<i32> to i64
// CHECK:           %[[VAL_26:.*]] = arith.remsi %[[VAL_25]], %[[VAL_14]] : i64
// CHECK:           %[[VAL_27:.*]] = tptr.ptradd %[[VAL_21]] %[[VAL_13]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:           %[[VAL_28:.*]] = tptr.ptradd %[[VAL_27]] %[[VAL_26]] : !tt.ptr<i32>, i64 to !tt.ptr<i32>
// CHECK:           %[[VAL_29:.*]] = builtin.unrealized_conversion_cast %[[VAL_28]] : !tt.ptr<i32> to !tt.ptr<i64>
// CHECK:           %[[VAL_30:.*]] = tptr.ptradd %[[VAL_29]] %[[VAL_12]] : !tt.ptr<i64>, i32 to !tt.ptr<i64>
// CHECK:           %[[VAL_31:.*]] = tptr.ptradd %[[VAL_30]] %[[VAL_2]] : !tt.ptr<i64>, i32 to !tt.ptr<i64>
// CHECK:           %[[VAL_32:.*]] = tptr.ptradd %[[VAL_31]] %[[VAL_11]] : !tt.ptr<i64>, i32 to !tt.ptr<i64>
// CHECK:           %[[VAL_33:.*]] = builtin.unrealized_conversion_cast %[[VAL_32]] : !tt.ptr<i64> to !tt.ptr<i16>
// CHECK:           %[[VAL_34:.*]] = tptr.ptradd %[[VAL_33]] %[[VAL_10]] : !tt.ptr<i16>, i32 to !tt.ptr<i16>
// CHECK:           %[[VAL_35:.*]] = tptr.ptradd %[[VAL_34]] %[[VAL_2]] : !tt.ptr<i16>, i32 to !tt.ptr<i16>
// CHECK:           %[[VAL_36:.*]] = tptr.ptradd %[[VAL_35]] %[[VAL_11]] : !tt.ptr<i16>, i32 to !tt.ptr<i16>
// CHECK:           %[[VAL_37:.*]] = builtin.unrealized_conversion_cast %[[VAL_36]] : !tt.ptr<i16> to !tt.ptr<i32>
// CHECK:           %[[VAL_38:.*]] = tptr.to_memref %[[VAL_37]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:           %[[VAL_39:.*]] = memref.load %[[VAL_38]]{{\[}}%[[VAL_9]]] : memref<1xi32>
// CHECK:           %[[VAL_40:.*]] = arith.extsi %[[VAL_2]] : i32 to i64
// CHECK:           %[[VAL_41:.*]] = arith.addi %[[VAL_26]], %[[VAL_40]] : i64
// CHECK:           %[[VAL_42:.*]] = tptr.inttoptr %[[VAL_41]] : i64 to !tt.ptr<i32>
// CHECK:           %[[VAL_43:.*]] = tptr.to_memref %[[VAL_42]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:           memref.store %[[VAL_39]], %[[VAL_43]]{{\[}}%[[VAL_9]]] : memref<1xi32>
// CHECK:           return
// CHECK:         }



