// RUN: triton-shared-opt --triton-arith-to-linalg="tensor-ptr-to-linalg" --triton-to-ptr --cse --canonicalize %s | FileCheck %s
// Original triton program:
//    @triton.jit
//    def ptr_cat(in_ptr0, out_ptr0, mask_ptr):
//        offsets = tl.arange(0, 16)
//        ptr_0 = in_ptr0 + tl.arange(0, 8)
//        ptr_1 = out_ptr0 + tl.arange(0, 8)
//        ptr = tl.cat(ptr_0, ptr_1, can_reorder=True)
//        ptr_true = ptr + 4 * tl.load(offsets + ptr)
//        ptr_false = ptr + 5 * tl.load(offsets + ptr)
//        masks = tl.load(mask_ptr + offsets)
//        ptr_load = tl.where(masks, ptr_true, ptr_false)
//        a = tl.load(ptr_load + offsets, mask=masks)
//        tl.store(out_ptr0 + offsets, a, mask=masks)

module {
  tt.func public @ptr_cat(%arg0: !tt.ptr<i32>, %arg1: !tt.ptr<i32>, %arg2: !tt.ptr<i1>) attributes {noinline = false} {
    %cst = arith.constant dense<0> : tensor<16xi8>
    %cst_0 = arith.constant dense<5> : tensor<16xi32>
    %cst_1 = arith.constant dense<4> : tensor<16xi32>
    %0 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %1 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32>
    %2 = tt.splat %arg0 : !tt.ptr<i32> -> tensor<8x!tt.ptr<i32>>
    %3 = tt.addptr %2, %1 : tensor<8x!tt.ptr<i32>>, tensor<8xi32>
    %4 = tt.splat %arg1 : !tt.ptr<i32> -> tensor<8x!tt.ptr<i32>>
    %5 = tt.addptr %4, %1 : tensor<8x!tt.ptr<i32>>, tensor<8xi32>
    %6 = tt.cat %3, %5 : tensor<8x!tt.ptr<i32>> -> tensor<16x!tt.ptr<i32>>
    %7 = tt.addptr %6, %0 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %8 = tt.load %7 : tensor<16x!tt.ptr<i32>>
    %9 = arith.muli %8, %cst_1 : tensor<16xi32>
    %10 = tt.addptr %6, %9 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %11 = arith.muli %8, %cst_0 : tensor<16xi32>
    %12 = tt.addptr %6, %11 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %13 = tt.splat %arg2 : !tt.ptr<i1> -> tensor<16x!tt.ptr<i1>>
    %14 = tt.addptr %13, %0 : tensor<16x!tt.ptr<i1>>, tensor<16xi32>
    %15 = tt.bitcast %14 : tensor<16x!tt.ptr<i1>> -> tensor<16x!tt.ptr<i8>>
    %16 = tt.load %15 : tensor<16x!tt.ptr<i8>>
    %17 = arith.cmpi ne, %16, %cst : tensor<16xi8>
    %18 = arith.select %17, %10, %12 : tensor<16xi1>, tensor<16x!tt.ptr<i32>>
    %19 = tt.addptr %18, %0 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %20 = tt.load %19, %17 : tensor<16x!tt.ptr<i32>>
    %21 = tt.splat %arg1 : !tt.ptr<i32> -> tensor<16x!tt.ptr<i32>>
    %22 = tt.addptr %21, %0 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    tt.store %22, %20, %17 : tensor<16x!tt.ptr<i32>>
    tt.return
  }
}
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>

// CHECK-LABEL:   func.func @ptr_cat(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<i32>, %[[VAL_1:.*]]: !tt.ptr<i32>, %[[VAL_2:.*]]: !tt.ptr<i1>, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK-DAG:           %[[VAL_9:.*]] = arith.constant 0 : i32
// CHECK-DAG:           %[[VAL_10:.*]] = arith.constant 0 : index
// CHECK-DAG:           %[[VAL_11:.*]] = arith.constant 4 : i32
// CHECK-DAG:           %[[VAL_12:.*]] = arith.constant 5 : i32
// CHECK-DAG:           %[[VAL_13:.*]] = arith.constant 0 : i8
// CHECK-DAG:           %[[VAL_14:.*]] = tensor.empty() : tensor<16xi8>
// CHECK-NOT: separator of consecutive DAGs
// CHECK-DAG:           %[[VAL_15:.*]] = linalg.fill ins(%[[VAL_13]] : i8) outs(%[[VAL_14]] : tensor<16xi8>) -> tensor<16xi8>
// CHECK-DAG:           %[[VAL_16:.*]] = tensor.empty() : tensor<16xi32>
// CHECK-NOT: separator of consecutive DAGs
// CHECK-DAG:           %[[VAL_17:.*]] = linalg.fill ins(%[[VAL_12]] : i32) outs(%[[VAL_16]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK-DAG:           %[[VAL_18:.*]] = linalg.fill ins(%[[VAL_11]] : i32) outs(%[[VAL_16]] : tensor<16xi32>) -> tensor<16xi32>
// CHECK-DAG:           %[[VAL_19:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_16]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_20:.*]]: i32):
// CHECK:             %[[VAL_21:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_22:.*]] = arith.index_cast %[[VAL_21]] : index to i32
// CHECK:             linalg.yield %[[VAL_22]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_23:.*]] = tensor.empty() : tensor<8xi32>
// CHECK:           %[[VAL_24:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_23]] : tensor<8xi32>) {
// CHECK:           ^bb0(%[[VAL_25:.*]]: i32):
// CHECK:             %[[VAL_26:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_27:.*]] = arith.index_cast %[[VAL_26]] : index to i32
// CHECK:             linalg.yield %[[VAL_27]] : i32
// CHECK:           } -> tensor<8xi32>
// CHECK:           %[[VAL_28:.*]] = tensor.empty() : tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_29:.*]] = linalg.fill ins(%[[VAL_0]] : !tt.ptr<i32>) outs(%[[VAL_28]] : tensor<8x!tt.ptr<i32>>) -> tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_30:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_29]], %[[VAL_24]] : tensor<8x!tt.ptr<i32>>, tensor<8xi32>) outs(%[[VAL_29]] : tensor<8x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_31:.*]]: !tt.ptr<i32>, %[[VAL_32:.*]]: i32, %[[VAL_33:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_34:.*]] = tptr.ptradd %[[VAL_31]] %[[VAL_32]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_34]] : !tt.ptr<i32>
// CHECK:           } -> tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_35:.*]] = linalg.fill ins(%[[VAL_1]] : !tt.ptr<i32>) outs(%[[VAL_28]] : tensor<8x!tt.ptr<i32>>) -> tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_36:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_35]], %[[VAL_24]] : tensor<8x!tt.ptr<i32>>, tensor<8xi32>) outs(%[[VAL_35]] : tensor<8x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_37:.*]]: !tt.ptr<i32>, %[[VAL_38:.*]]: i32, %[[VAL_39:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_40:.*]] = tptr.ptradd %[[VAL_37]] %[[VAL_38]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_40]] : !tt.ptr<i32>
// CHECK:           } -> tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_41:.*]] = tensor.empty() : tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_42:.*]] = tensor.insert_slice %[[VAL_30]] into %[[VAL_41]][0] [8] [1] : tensor<8x!tt.ptr<i32>> into tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_43:.*]] = tensor.insert_slice %[[VAL_36]] into %[[VAL_42]][8] [8] [1] : tensor<8x!tt.ptr<i32>> into tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_44:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_43]], %[[VAL_19]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>) outs(%[[VAL_43]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_45:.*]]: !tt.ptr<i32>, %[[VAL_46:.*]]: i32, %[[VAL_47:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_48:.*]] = tptr.ptradd %[[VAL_45]] %[[VAL_46]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_48]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_49:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_44]] : tensor<16x!tt.ptr<i32>>) outs(%[[VAL_16]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_50:.*]]: !tt.ptr<i32>, %[[VAL_51:.*]]: i32):
// CHECK:             %[[VAL_52:.*]] = tptr.to_memref %[[VAL_50]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:             %[[VAL_53:.*]] = memref.load %[[VAL_52]]{{\[}}%[[VAL_10]]] : memref<1xi32>
// CHECK:             linalg.yield %[[VAL_53]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_54:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_49]], %[[VAL_18]] : tensor<16xi32>, tensor<16xi32>) outs(%[[VAL_49]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_55:.*]]: i32, %[[VAL_56:.*]]: i32, %[[VAL_57:.*]]: i32):
// CHECK:             %[[VAL_58:.*]] = arith.muli %[[VAL_55]], %[[VAL_56]] : i32
// CHECK:             linalg.yield %[[VAL_58]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_59:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_43]], %[[VAL_54]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>) outs(%[[VAL_43]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_60:.*]]: !tt.ptr<i32>, %[[VAL_61:.*]]: i32, %[[VAL_62:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_63:.*]] = tptr.ptradd %[[VAL_60]] %[[VAL_61]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_63]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_64:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_49]], %[[VAL_17]] : tensor<16xi32>, tensor<16xi32>) outs(%[[VAL_49]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_65:.*]]: i32, %[[VAL_66:.*]]: i32, %[[VAL_67:.*]]: i32):
// CHECK:             %[[VAL_68:.*]] = arith.muli %[[VAL_65]], %[[VAL_66]] : i32
// CHECK:             linalg.yield %[[VAL_68]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_69:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_43]], %[[VAL_64]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>) outs(%[[VAL_43]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_70:.*]]: !tt.ptr<i32>, %[[VAL_71:.*]]: i32, %[[VAL_72:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_73:.*]] = tptr.ptradd %[[VAL_70]] %[[VAL_71]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_73]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_74:.*]] = tensor.empty() : tensor<16x!tt.ptr<i1>>
// CHECK:           %[[VAL_75:.*]] = linalg.fill ins(%[[VAL_2]] : !tt.ptr<i1>) outs(%[[VAL_74]] : tensor<16x!tt.ptr<i1>>) -> tensor<16x!tt.ptr<i1>>
// CHECK:           %[[VAL_76:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_75]], %[[VAL_19]] : tensor<16x!tt.ptr<i1>>, tensor<16xi32>) outs(%[[VAL_75]] : tensor<16x!tt.ptr<i1>>) {
// CHECK:           ^bb0(%[[VAL_77:.*]]: !tt.ptr<i1>, %[[VAL_78:.*]]: i32, %[[VAL_79:.*]]: !tt.ptr<i1>):
// CHECK:             %[[VAL_80:.*]] = tptr.ptradd %[[VAL_77]] %[[VAL_78]] : !tt.ptr<i1>, i32 to !tt.ptr<i1>
// CHECK:             linalg.yield %[[VAL_80]] : !tt.ptr<i1>
// CHECK:           } -> tensor<16x!tt.ptr<i1>>
// CHECK:           %[[VAL_81:.*]] = tensor.empty() : tensor<16x!tt.ptr<i8>>
// CHECK:           %[[VAL_82:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_76]] : tensor<16x!tt.ptr<i1>>) outs(%[[VAL_81]] : tensor<16x!tt.ptr<i8>>) {
// CHECK:           ^bb0(%[[VAL_83:.*]]: !tt.ptr<i1>, %[[VAL_84:.*]]: !tt.ptr<i8>):
// CHECK:             %[[VAL_85:.*]] = builtin.unrealized_conversion_cast %[[VAL_83]] : !tt.ptr<i1> to !tt.ptr<i8>
// CHECK:             linalg.yield %[[VAL_85]] : !tt.ptr<i8>
// CHECK:           } -> tensor<16x!tt.ptr<i8>>
// CHECK:           %[[VAL_86:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_82]] : tensor<16x!tt.ptr<i8>>) outs(%[[VAL_14]] : tensor<16xi8>) {
// CHECK:           ^bb0(%[[VAL_87:.*]]: !tt.ptr<i8>, %[[VAL_88:.*]]: i8):
// CHECK:             %[[VAL_89:.*]] = tptr.to_memref %[[VAL_87]] : !tt.ptr<i8> to memref<1xi8>
// CHECK:             %[[VAL_90:.*]] = memref.load %[[VAL_89]]{{\[}}%[[VAL_10]]] : memref<1xi8>
// CHECK:             linalg.yield %[[VAL_90]] : i8
// CHECK:           } -> tensor<16xi8>
// CHECK:           %[[VAL_91:.*]] = tensor.empty() : tensor<16xi1>
// CHECK:           %[[VAL_92:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_86]], %[[VAL_15]] : tensor<16xi8>, tensor<16xi8>) outs(%[[VAL_91]] : tensor<16xi1>) {
// CHECK:           ^bb0(%[[VAL_93:.*]]: i8, %[[VAL_94:.*]]: i8, %[[VAL_95:.*]]: i1):
// CHECK:             %[[VAL_96:.*]] = arith.cmpi ne, %[[VAL_93]], %[[VAL_94]] : i8
// CHECK:             linalg.yield %[[VAL_96]] : i1
// CHECK:           } -> tensor<16xi1>
// CHECK:           %[[VAL_97:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_92]], %[[VAL_59]], %[[VAL_69]] : tensor<16xi1>, tensor<16x!tt.ptr<i32>>, tensor<16x!tt.ptr<i32>>) outs(%[[VAL_59]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_98:.*]]: i1, %[[VAL_99:.*]]: !tt.ptr<i32>, %[[VAL_100:.*]]: !tt.ptr<i32>, %[[VAL_101:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_102:.*]] = arith.select %[[VAL_98]], %[[VAL_99]], %[[VAL_100]] : !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_102]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_103:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_97]], %[[VAL_19]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>) outs(%[[VAL_97]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_104:.*]]: !tt.ptr<i32>, %[[VAL_105:.*]]: i32, %[[VAL_106:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_107:.*]] = tptr.ptradd %[[VAL_104]] %[[VAL_105]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_107]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_108:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_103]], %[[VAL_92]] : tensor<16x!tt.ptr<i32>>, tensor<16xi1>) outs(%[[VAL_16]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_109:.*]]: !tt.ptr<i32>, %[[VAL_110:.*]]: i1, %[[VAL_111:.*]]: i32):
// CHECK-DAG:             %[[VAL_112:.*]] = tptr.to_memref %[[VAL_109]] : !tt.ptr<i32> to memref<1xi32>
// CHECK-DAG:             %[[VAL_113:.*]] = scf.if %[[VAL_110]] -> (i32) {
// CHECK:               %[[VAL_114:.*]] = memref.load %[[VAL_112]]{{\[}}%[[VAL_10]]] : memref<1xi32>
// CHECK:               scf.yield %[[VAL_114]] : i32
// CHECK:             } else {
// CHECK:               scf.yield %[[VAL_9]] : i32
// CHECK:             }
// CHECK:             linalg.yield %[[VAL_113]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[VAL_115:.*]] = linalg.fill ins(%[[VAL_1]] : !tt.ptr<i32>) outs(%[[VAL_41]] : tensor<16x!tt.ptr<i32>>) -> tensor<16x!tt.ptr<i32>>
// CHECK:           %[[VAL_116:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_115]], %[[VAL_19]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>) outs(%[[VAL_115]] : tensor<16x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_117:.*]]: !tt.ptr<i32>, %[[VAL_118:.*]]: i32, %[[VAL_119:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_120:.*]] = tptr.ptradd %[[VAL_117]] %[[VAL_118]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_120]] : !tt.ptr<i32>
// CHECK:           } -> tensor<16x!tt.ptr<i32>>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_116]], %[[VAL_108]], %[[VAL_92]] : tensor<16x!tt.ptr<i32>>, tensor<16xi32>, tensor<16xi1>) {
// CHECK:           ^bb0(%[[VAL_121:.*]]: !tt.ptr<i32>, %[[VAL_122:.*]]: i32, %[[VAL_123:.*]]: i1):
// CHECK:             scf.if %[[VAL_123]] {
// CHECK:               %[[VAL_124:.*]] = tptr.to_memref %[[VAL_121]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:               memref.store %[[VAL_122]], %[[VAL_124]]{{\[}}%[[VAL_10]]] : memref<1xi32>
// CHECK:             }
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           return
// CHECK:         }
