// Test that triton load and store with mask are lowered correctly
// (scf.if guarding the load and store)
// RUN: triton-shared-opt --triton-arith-to-linalg="tensor-ptr-to-linalg" --triton-to-ptr --cse --canonicalize %s | FileCheck %s

module {
  tt.func public @tensor_ptr(%arg0: !tt.ptr<i32>, %arg1: !tt.ptr<i32>) attributes {noinline = false} {
    %cst = arith.constant dense<2> : tensor<16xi32>
    %cst_0 = arith.constant dense<0> : tensor<16xi32>
    %cst_1 = arith.constant dense<16> : tensor<16xi32>
    %0 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %1 = tt.splat %arg0 : !tt.ptr<i32> -> tensor<16x!tt.ptr<i32>>
    %2 = tt.addptr %1, %0 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %3 = tt.load %2 : tensor<16x!tt.ptr<i32>>
    %4 = arith.extsi %3 : tensor<16xi32> to tensor<16xi64>
    %5 = tt.int_to_ptr %4 : tensor<16xi64> -> tensor<16x!tt.ptr<i32>>
    %6 = tt.addptr %5, %cst_1 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %7 = tt.load %6 : tensor<16x!tt.ptr<i32>>
    %8 = arith.cmpi ne, %7, %cst_0 : tensor<16xi32>
    %9 = tt.load %5, %8 : tensor<16x!tt.ptr<i32>>
    %10 = tt.splat %arg1 : !tt.ptr<i32> -> tensor<16x!tt.ptr<i32>>
    %11 = tt.addptr %10, %0 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %12 = tt.ptr_to_int %11 : tensor<16x!tt.ptr<i32>> -> tensor<16xi64>
    %13 = arith.extsi %9 : tensor<16xi32> to tensor<16xi64>
    %14 = arith.addi %12, %13 : tensor<16xi64>
    %15 = tt.bitcast %11 : tensor<16x!tt.ptr<i32>> -> tensor<16x!tt.ptr<i64>>
    %16 = tt.addptr %15, %cst : tensor<16x!tt.ptr<i64>>, tensor<16xi32>
    %17 = tt.bitcast %16 : tensor<16x!tt.ptr<i64>> -> tensor<16x!tt.ptr<i32>>
    %18 = arith.trunci %14 : tensor<16xi64> to tensor<16xi32>
    tt.store %17, %18, %8 : tensor<16x!tt.ptr<i32>>
    tt.return
  }
}

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>

// CHECK-COUNT-7: linalg.generic

// CHECK:    %[[VAL_51:.*]] = tensor.empty() : tensor<16xi1>
// CHECK:    %[[VAL_52:.*]] = linalg.generic
// CHECK:    ^bb0(%[[VAL_53:.*]]: i32, %[[VAL_54:.*]]: i32, %[[VAL_55:.*]]: i1):
// CHECK:      %[[VAL_56:.*]] = arith.cmpi ne, %[[VAL_53]], %[[VAL_54]] : i32
// CHECK:      linalg.yield %[[VAL_56]] : i1
// CHECK:    } -> tensor<16xi1>

// CHECK:    %[[VAL_57:.*]] = linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel"]} ins(%{{.+}}, %{{.+}} : tensor<16x!tt.ptr<i32>>, tensor<16xi1>) outs(%{{.+}} : tensor<16xi32>) {
// CHECK:    ^bb0(%[[VAL_58:.*]]: !tt.ptr<i32>, %[[VAL_59:.*]]: i1, %[[VAL_60:.*]]: i32):
// CHECK:      %[[VAL_61:.*]] = tptr.to_memref %[[VAL_58]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:      %[[VAL_62:.*]] = scf.if %[[VAL_59]] -> (i32) {
// CHECK:        %[[VAL_63:.*]] = memref.load %[[VAL_61]]{{\[}}%{{.+}} : memref<1xi32>
// CHECK:        scf.yield %[[VAL_63]] : i32
// CHECK:      } else {
// CHECK:        scf.yield %{{.+}} : i32
// CHECK:      }
// CHECK:      linalg.yield %[[VAL_62]] : i32
// CHECK:    } -> tensor<16xi32>

// CHECK:    linalg.generic {indexing_maps = [#map, #map, #map], iterator_types = ["parallel"]} ins(%{{.+}}, %{{.+}}, %{{.+}} : tensor<16x!tt.ptr<i32>>, tensor<16xi32>, tensor<16xi1>) {
// CHECK:    ^bb0(%[[VAL_101:.*]]: !tt.ptr<i32>, %[[VAL_102:.*]]: i32, %[[VAL_103:.*]]: i1):
// CHECK:      scf.if %[[VAL_103]] {
// CHECK:        %[[VAL_104:.*]] = tptr.to_memref %[[VAL_101]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:        memref.store %[[VAL_102]], %[[VAL_104]]{{\[}}%{{.+}}] : memref<1xi32>
// CHECK:      }
// CHECK:      linalg.yield
// CHECK:    }
