// RUN: triton-shared-opt --triton-arith-to-linalg="tensor-ptr-to-linalg"  --triton-to-ptr --canonicalize --cse %s | FileCheck %s

module {
  tt.func @kernel(%a : !tt.ptr<i32>, %b : !tt.ptr<f32>) -> () {
    // offset calculations
    %0 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>

    // a pointer
    %8 = tt.splat %a : !tt.ptr<i32> -> tensor<1024x!tt.ptr<i32>>
    %9 = tt.addptr %8, %0 : tensor<1024x!tt.ptr<i32>>, tensor<1024xi32>

    // b pointer
    %18 = tt.splat %b : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %19 = tt.addptr %18, %0 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>

    %am = tt.load %9 : tensor<1024x!tt.ptr<i32>>

    %am_bitcast = tt.bitcast %am : tensor<1024xi32> -> tensor<1024xf32>
    tt.store %19, %am_bitcast : tensor<1024x!tt.ptr<f32>>
    tt.return
  }
}

// CHECK// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>

// CHECK-LABEL:   func.func @kernel(
// CHECK-SAME:  %[[VAL_0:.*]]: !tt.ptr<i32>, %[[VAL_1:.*]]: !tt.ptr<f32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32) {
// CHECK:           %[[VAL_8:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_9:.*]] = tensor.empty() : tensor<1024xi32>
// CHECK:           %[[VAL_10:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_9]] : tensor<1024xi32>) {
// CHECK:           ^bb0(%[[VAL_11:.*]]: i32):
// CHECK:             %[[VAL_12:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_13:.*]] = arith.index_cast %[[VAL_12]] : index to i32
// CHECK:             linalg.yield %[[VAL_13]] : i32
// CHECK:           } -> tensor<1024xi32>
// CHECK:           %[[VAL_14:.*]] = tensor.empty() : tensor<1024x!tt.ptr<i32>>
// CHECK:           %[[VAL_15:.*]] = linalg.fill ins(%[[VAL_0]] : !tt.ptr<i32>) outs(%[[VAL_14]] : tensor<1024x!tt.ptr<i32>>) -> tensor<1024x!tt.ptr<i32>>
// CHECK:           %[[VAL_16:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_15]], %[[VAL_10]] : tensor<1024x!tt.ptr<i32>>, tensor<1024xi32>) outs(%[[VAL_15]] : tensor<1024x!tt.ptr<i32>>) {
// CHECK:           ^bb0(%[[VAL_17:.*]]: !tt.ptr<i32>, %[[VAL_18:.*]]: i32, %[[VAL_19:.*]]: !tt.ptr<i32>):
// CHECK:             %[[VAL_20:.*]] = tptr.ptradd %[[VAL_17]] %[[VAL_18]] : !tt.ptr<i32>, i32 to !tt.ptr<i32>
// CHECK:             linalg.yield %[[VAL_20]] : !tt.ptr<i32>
// CHECK:           } -> tensor<1024x!tt.ptr<i32>>
// CHECK:           %[[VAL_21:.*]] = tensor.empty() : tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[VAL_22:.*]] = linalg.fill ins(%[[VAL_1]] : !tt.ptr<f32>) outs(%[[VAL_21]] : tensor<1024x!tt.ptr<f32>>) -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[VAL_23:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_22]], %[[VAL_10]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>) outs(%[[VAL_22]] : tensor<1024x!tt.ptr<f32>>) {
// CHECK:           ^bb0(%[[VAL_24:.*]]: !tt.ptr<f32>, %[[VAL_25:.*]]: i32, %[[VAL_26:.*]]: !tt.ptr<f32>):
// CHECK:             %[[VAL_27:.*]] = tptr.ptradd %[[VAL_24]] %[[VAL_25]] : !tt.ptr<f32>, i32 to !tt.ptr<f32>
// CHECK:             linalg.yield %[[VAL_27]] : !tt.ptr<f32>
// CHECK:           } -> tensor<1024x!tt.ptr<f32>>
// CHECK:           %[[VAL_28:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_16]] : tensor<1024x!tt.ptr<i32>>) outs(%[[VAL_9]] : tensor<1024xi32>) {
// CHECK:           ^bb0(%[[VAL_29:.*]]: !tt.ptr<i32>, %[[VAL_30:.*]]: i32):
// CHECK:             %[[VAL_31:.*]] = tptr.to_memref %[[VAL_29]] : !tt.ptr<i32> to memref<1xi32>
// CHECK:             %[[VAL_32:.*]] = memref.load %[[VAL_31]]{{\[}}%[[VAL_8]]] : memref<1xi32>
// CHECK:             linalg.yield %[[VAL_32]] : i32
// CHECK:           } -> tensor<1024xi32>
// CHECK:           %[[VAL_33:.*]] = tensor.empty() : tensor<1024xf32>
// CHECK:           %[[VAL_34:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_28]] : tensor<1024xi32>) outs(%[[VAL_33]] : tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_35:.*]]: i32, %[[VAL_36:.*]]: f32):
// CHECK:             %[[VAL_37:.*]] = arith.bitcast %[[VAL_35]] : i32 to f32
// CHECK:             linalg.yield %[[VAL_37]] : f32
// CHECK:           } -> tensor<1024xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_23]], %[[VAL_34]] : tensor<1024x!tt.ptr<f32>>, tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_38:.*]]: !tt.ptr<f32>, %[[VAL_39:.*]]: f32):
// CHECK:             %[[VAL_40:.*]] = tptr.to_memref %[[VAL_38]] : !tt.ptr<f32> to memref<1xf32>
// CHECK:             memref.store %[[VAL_39]], %[[VAL_40]]{{\[}}%[[VAL_8]]] : memref<1xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           return
// CHECK:         }
