name: Integration Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      triton-ref:
        description: 'Triton Reference'
        required: true
        default: '0e3bf3f58061bd62725e7c502e7e0af19690df1c'
      triton-shared-ref:
        description: 'Triton Shared Reference'
        required: true

jobs:

  call-workflow:
    uses: ./.github/workflows/test-plugin.yml
    with:
        # [BACKEND] Fix layouts in nvgpu RewriteTensorPointer. (#2634)
        triton-ref: '0e3bf3f58061bd62725e7c502e7e0af19690df1c'
        triton-shared-ref: ${{ github.ref }}
